---
kind: pipeline
name: default

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/bdebyl/docker-awscli.git .
      - git checkout $DRONE_COMMIT
      - echo -n "1.0.$DRONE_BUILD_NUMBER" > .tags

  - name: gate-master
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only HEAD~1..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        - master

  - name: gate-pr
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        exclude:
          - master

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/awscli
    when:
      branch:
        - master
---
kind: signature
hmac: 61a0f4e8c2964ff223c2444d0c34fce4d9d37481f271bbe2e9446e0b79bc2f36

...
