---
kind: pipeline
type: docker
name: default

steps:
  - name: set tag
    image: docker.io/alpine-git/bdebyl/alpine-git
    commands:
      - echo -n "1.0.$DRONE_BUILD_NUMBER" > .tags

  - name: gate-master
    image: docker.io/alpine-git/bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only HEAD~1..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        - master

  - name: gate-pr
    image: docker.io/alpine-git/bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        exclude:
          - master

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/awscli
    when:
      branch:
        - master
---
kind: signature
hmac: 8dd8c083505460b712492c79ae4ec47d9c0a1af302bfb4df3125d9961875026d

...
